In [1]:
# Dependencies and Setup
import pandas as pd
import sklearn.datasets as dta
import scipy.stats as st
import matplotlib.pyplot as plt
import numpy as np
# File to Load (Remember to Change These)
file_to_load = "csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv"

# Read Purchasing File and store into Pandas data frame
df = pd.read_csv(file_to_load)

In [2]:
df

,UID,iso2,iso3,code3,FIPS,Admin2,Province_State,Country_Region,Lat,Long_,...,4/12/20,4/13/20,4/14/20,4/15/20,4/16/20,4/17/20,4/18/20,4/19/20,4/20/20,4/21/20
0,16,AS,ASM,16,60.0,NaN,American Samoa,US,-14.2710,-170.1320,...,0,0,0,0,0,0,0,0,0,0
1,316,GU,GUM,316,66.0,NaN,Guam,US,13.4443,144.7937,...,133,133,133,135,135,136,136,136,136,136
2,580,MP,MNP,580,69.0,NaN,Northern Mariana Islands,US,15.0979,145.6739,...,11,11,11,13,13,13,14,14,14,14
3,630,PR,PRI,630,72.0,NaN,Puerto Rico,US,18.2208,-66.5901,...,897,903,923,974,1043,1068,1118,1213,1252,1298
4,850,VI,VIR,850,78.0,NaN,Virgin Islands,US,18.3358,-64.8963,...,51,51,51,51,51,51,53,53,53,53
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3264,84070008,US,USA,840,NaN,Marine Corps,US Military,US,NaN,NaN,...,0,0,0,0,0,0,0,0,0,253
3265,84070009,US,USA,840,NaN,Navy,US Military,US,NaN,NaN,...,0,0,0,0,0,0,0,0,0,1631
3266,84070013,US,USA,840,NaN,Staff,Federal Bureau of Prisons,US,NaN,NaN,...,0,0,0,0,0,0,0,0,0,319
3267,84070010,US,USA,840,NaN,Unassigned,US Military,US,NaN,NaN,...,0,0,0,0,0,0,0,0,0,1810
3268,84070021,US,USA,840,NaN,NaN,Veteran Hospitals,US,NaN,NaN,...,0,0,0,0,0,0,0,0,0,5599

In [3]:
california_df = df.loc[df['Province_State'] == 'California']
california_df = california_df.drop(['Admin2','Province_State','Country_Region','UID','iso2','iso3','code3','FIPS','Lat','Long_','4/19/20','4/20/20','4/21/20'],axis = 1)
california_df = california_df.set_index('Combined_Key')
california_df

,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,1/30/20,1/31/20,...,4/9/20,4/10/20,4/11/20,4/12/20,4/13/20,4/14/20,4/15/20,4/16/20,4/17/20,4/18/20
Combined_Key,,,,,,,,,,,,,,,,,,,,,
"Alameda, California, US",0,0,0,0,0,0,0,0,0,0,...,674,766,806,845,888,888,964,1007,1063,1114
"Alpine, California, US",0,0,0,0,0,0,0,0,0,0,...,1,1,2,2,2,2,2,2,2,2
"Amador, California, US",0,0,0,0,0,0,0,0,0,0,...,3,7,7,7,7,7,7,7,7,7
"Butte, California, US",0,0,0,0,0,0,0,0,0,0,...,13,13,14,14,14,15,16,16,16,16
"Calaveras, California, US",0,0,0,0,0,0,0,0,0,0,...,5,8,8,8,8,9,9,11,11,12
"Colusa, California, US",0,0,0,0,0,0,0,0,0,0,...,3,3,3,3,3,3,3,3,3,3
"Contra Costa, California, US",0,0,0,0,0,0,0,0,0,0,...,484,511,530,539,552,552,615,631,648,685
"Del Norte, California, US",0,0,0,0,0,0,0,0,0,0,...,2,2,2,2,2,2,2,2,2,2
"El Dorado, California, US",0,0,0,0,0,0,0,0,0,0,...,29,30,32,32,32,34,35,35,36,36
"Fresno, California, US",0,0,0,0,0,0,0,0,0,0,...,156,173,191,201,201,222,251,265,295,311
"Glenn, California, US",0,0,0,0,0,0,0,0,0,0,...,2,3,3,3,3,4,4,4,4,4
"Humboldt, California, US",0,0,0,0,0,0,0,0,0,0,...,50,50,50,50,50,50,51,52,52,52
"Imperial, California, US",0,0,0,0,0,0,0,0,0,0,...,75,79,79,87,87,100,117,127,143,155
"Inyo, California, US",0,0,0,0,0,0,0,0,0,0,...,11,12,12,12,12,12,17,17,17,18
"Kern, California, US",0,0,0,0,0,0,0,0,0,0,...,303,337,371,396,436,462,533,565,578,610
"Kings, California, US",0,0,0,0,0,0,0,0,0,0,...,8,8,9,10,10,12,13,13,18,20
"Lake, California, US",0,0,0,0,0,0,0,0,0,0,...,3,4,4,4,4,4,5,6,6,6
"Lassen, California, US",0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
"Los Angeles, California, US",0,0,0,0,1,1,1,1,1,1,...,7955,8443,8453,8894,9433,10047,10517,10854,11400,12021
"Madera, California, US",0,0,0,0,0,0,0,0,0,0,...,28,30,32,32,33,33,33,33,33,33
"Marin, California, US",0,0,0,0,0,0,0,0,0,0,...,149,154,154,153,164,170,171,184,187,187
"Mariposa, California, US",0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
"Mendocino, California, US",0,0,0,0,0,0,0,0,0,0,...,4,4,4,4,4,4,4,4,4,5
"Merced, California, US",0,0,0,0,0,0,0,0,0,0,...,40,52,59,65,65,74,76,79,82,86
"Modoc, California, US",0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
"Mono, California, US",0,0,0,0,0,0,0,0,0,0,...,20,20,21,21,23,23,23,23,23,23
"Monterey, California, US",0,0,0,0,0,0,0,0,0,0,...,69,71,79,82,87,87,100,108,119,119
"Napa, California, US",0,0,0,0,0,0,0,0,0,0,...,25,32,32,34,34,38,38,39,44,47
"Nevada, California, US",0,0,0,0,0,0,0,0,0,0,...,34,34,34,34,34,34,34,34,34,36
"Orange, California, US",0,0,0,0,1,1,1,1,1,1,...,1079,1138,1221,1277,1283,1299,1376,1425,1501,1556
"Placer, California, US",0,0,0,0,0,0,0,0,0,0,...,117,123,123,124,127,128,129,130,130,131
"Plumas, California, US",0,0,0,0,0,0,0,0,0,0,...,3,3,4,4,4,4,4,4,4,4
"Riverside, California, US",0,0,0,0,0,0,0,0,0,0,...,1280,1350,1431,1619,1619,1961,1961,2105,2457,2457
"Sacramento, California, US",0,0,0,0,0,0,0,0,0,0,...,580,653,653,707,739,816,853,879,896,914
"San Benito, California, US",0,0,0,0,0,0,0,0,0,0,...,33,34,35,35,35,39,39,41,44,44
"San Bernardino, California, US",0,0,0,0,0,0,0,0,0,0,...,641,729,810,810,887,977,977,996,1032,1219
"San Diego, California, US",0,0,0,0,0,0,0,0,0,0,...,1530,1628,1693,1761,1804,1847,1930,2012,2087,2158
"San Francisco, California, US",0,0,0,0,0,0,0,0,0,0,...,724,797,857,872,957,987,1013,1019,1058,1137
"San Joaquin, California, US",0,0,0,0,0,0,0,0,0,0,...,237,253,257,266,293,314,341,365,371,400
"San Luis Obispo, California, US",0,0,0,0,0,0,0,0,0,0,...,102,104,110,114,117,117,120,125,127,131
"San Mateo, California, US",0,0,0,0,0,0,0,0,0,0,...,633,638,652,652,701,721,747,767,797,838
"Santa Barbara, California, US",0,0,0,0,0,0,0,0,0,0,...,228,243,260,264,267,284,313,334,354,373
"Santa Clara, California, US",0,0,0,0,0,0,0,0,0,1,...,1380,1442,1484,1566,1666,1666,1793,1833,1870,1870
"Santa Cruz, California, US",0,0,0,0,0,0,0,0,0,0,...,76,80,80,88,91,91,96,96,98,101
"Shasta, California, US",0,0,0,0,0,0,0,0,0,0,...,24,24,24,24,24,25,25,25,26,26
"Sierra, California, US",0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
"Siskiyou, California, US",0,0,0,0,0,0,0,0,0,0,...,4,5,5,5,5,5,5,5,5,5
"Solano, California, US",0,0,0,0,0,0,0,0,0,0,...,112,115,121,121,121,135,140,141,169,169
"Sonoma, California, US",0,0,0,0,0,0,0,0,0,0,...,136,142,145,145,147,152,160,163,172,180
"Stanislaus, California, US",0,0,0,0,0,0,0,0,0,0,...,95,103,116,121,131,146,163,177,187,206
"Sutter, California, US",0,0,0,0,0,0,0,0,0,0,...,20,37,37,37,37,23,24,24,24,25
"Tehama, California, US",0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
"Trinity, California, US",0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
"Tulare, California, US",0,0,0,0,0,0,0,0,0,0,...,168,203,203,227,264,296,352,372,382,397
"Tuolumne, California, US",0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,2,2,2,2
"Ventura, California, US",0,0,0,0,0,0,0,0,0,0,...,274,298,298,309,314,317,365,384,396,396
"Yolo, California, US",0,0,0,0,0,0,0,0,0,0,...,67,71,75,88,93,101,102,116,125,126
"Yuba, California, US",0,0,0,0,0,0,0,0,0,0,...,15,15,15,15,15,15,15,15,15,15
"Out of CA, California, US",0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
"Unassigned, California, US",0,0,0,0,0,0,0,0,0,0,...,4,4,4,8,0,0,0,0,0,0

In [4]:
#Check for any null value in dataframe 
null_data = california_df[california_df.isnull().any(axis=1)]
null_data

Empty DataFrame
Columns: [1/22/20, 1/23/20, 1/24/20, 1/25/20, 1/26/20, 1/27/20, 1/28/20, 1/29/20, 1/30/20, 1/31/20, 2/1/20, 2/2/20, 2/3/20, 2/4/20, 2/5/20, 2/6/20, 2/7/20, 2/8/20, 2/9/20, 2/10/20, 2/11/20, 2/12/20, 2/13/20, 2/14/20, 2/15/20, 2/16/20, 2/17/20, 2/18/20, 2/19/20, 2/20/20, 2/21/20, 2/22/20, 2/23/20, 2/24/20, 2/25/20, 2/26/20, 2/27/20, 2/28/20, 2/29/20, 3/1/20, 3/2/20, 3/3/20, 3/4/20, 3/5/20, 3/6/20, 3/7/20, 3/8/20, 3/9/20, 3/10/20, 3/11/20, 3/12/20, 3/13/20, 3/14/20, 3/15/20, 3/16/20, 3/17/20, 3/18/20, 3/19/20, 3/20/20, 3/21/20, 3/22/20, 3/23/20, 3/24/20, 3/25/20, 3/26/20, 3/27/20, 3/28/20, 3/29/20, 3/30/20, 3/31/20, 4/1/20, 4/2/20, 4/3/20, 4/4/20, 4/5/20, 4/6/20, 4/7/20, 4/8/20, 4/9/20, 4/10/20, 4/11/20, 4/12/20, 4/13/20, 4/14/20, 4/15/20, 4/16/20, 4/17/20, 4/18/20]
Index: []

[0 rows x 88 columns]

In [5]:
#Find the first date of infection, which is when sum(infection number) > 0 
#1/26/20 is the first confirmed date in California 
california_df_sum= california_df.sum(axis = 0)
print(california_df_sum)

1/22/20        0
1/23/20        0
1/24/20        0
1/25/20        0
1/26/20        2
           ...
4/14/20    25356
4/15/20    26686
4/16/20    27677
4/17/20    29157
4/18/20    30491
Length: 88, dtype: int64

In [6]:
#Orginztion and pick out the important date 
ca_key_date_df= california_df[['1/25/20','1/26/20','3/18/20','3/19/20','3/20/20','4/18/20']]
ca_key_date_df

,1/25/20,1/26/20,3/18/20,3/19/20,3/20/20,4/18/20
Combined_Key,,,,,,
"Alameda, California, US",0,0,30,38,48,1114
"Alpine, California, US",0,0,0,0,0,2
"Amador, California, US",0,0,0,0,0,7
"Butte, California, US",0,0,0,0,0,16
"Calaveras, California, US",0,0,2,2,2,12
"Colusa, California, US",0,0,0,0,0,3
"Contra Costa, California, US",0,0,39,41,46,685
"Del Norte, California, US",0,0,0,0,0,2
"El Dorado, California, US",0,0,0,0,0,36
"Fresno, California, US",0,0,2,3,6,311
"Glenn, California, US",0,0,0,0,0,4
"Humboldt, California, US",0,0,1,1,1,52
"Imperial, California, US",0,0,2,2,4,155
"Inyo, California, US",0,0,0,0,0,18
"Kern, California, US",0,0,1,3,4,610
"Kings, California, US",0,0,0,0,0,20
"Lake, California, US",0,0,0,0,0,6
"Lassen, California, US",0,0,0,0,0,0
"Los Angeles, California, US",0,1,190,231,292,12021
"Madera, California, US",0,0,1,1,3,33
"Marin, California, US",0,0,15,15,38,187
"Mariposa, California, US",0,0,0,0,0,0
"Mendocino, California, US",0,0,0,1,1,5
"Merced, California, US",0,0,0,0,0,86
"Modoc, California, US",0,0,0,0,0,0
"Mono, California, US",0,0,0,0,0,23
"Monterey, California, US",0,0,2,4,5,119
"Napa, California, US",0,0,0,0,0,47
"Nevada, California, US",0,0,1,1,1,36
"Orange, California, US",0,1,29,53,65,1556
"Placer, California, US",0,0,9,9,9,131
"Plumas, California, US",0,0,0,0,0,4
"Riverside, California, US",0,0,16,22,28,2457
"Sacramento, California, US",0,0,40,45,53,914
"San Benito, California, US",0,0,3,3,5,44
"San Bernardino, California, US",0,0,3,5,9,1219
"San Diego, California, US",0,0,60,80,127,2158
"San Francisco, California, US",0,0,51,70,76,1137
"San Joaquin, California, US",0,0,14,17,25,400
"San Luis Obispo, California, US",0,0,7,13,16,131
"San Mateo, California, US",0,0,80,89,100,838
"Santa Barbara, California, US",0,0,2,8,9,373
"Santa Clara, California, US",0,0,175,189,196,1870
"Santa Cruz, California, US",0,0,13,14,15,101
"Shasta, California, US",0,0,1,1,1,26
"Sierra, California, US",0,0,0,0,0,0
"Siskiyou, California, US",0,0,0,0,0,5
"Solano, California, US",0,0,8,8,13,169
"Sonoma, California, US",0,0,8,6,9,180
"Stanislaus, California, US",0,0,5,5,5,206
"Sutter, California, US",0,0,0,0,0,25
"Tehama, California, US",0,0,0,0,0,1
"Trinity, California, US",0,0,0,0,0,0
"Tulare, California, US",0,0,4,7,7,397
"Tuolumne, California, US",0,0,0,0,0,2
"Ventura, California, US",0,0,10,13,19,396
"Yolo, California, US",0,0,4,5,5,126
"Yuba, California, US",0,0,0,0,0,15
"Out of CA, California, US",0,0,0,0,0,0
"Unassigned, California, US",0,0,0,0,0,0

In [7]:
infection_rate_shelter = ca_key_date_df['4/18/20'] - ca_key_date_df['3/18/20']
ca_key_date_df['Infection number after shelter at home'] = infection_rate_shelter
ca_key_date_df

C:\Users\ericw\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,1/25/20,1/26/20,3/18/20,3/19/20,3/20/20,4/18/20,Infection number after shelter at home
Combined_Key,,,,,,,
"Alameda, California, US",0,0,30,38,48,1114,1084
"Alpine, California, US",0,0,0,0,0,2,2
"Amador, California, US",0,0,0,0,0,7,7
"Butte, California, US",0,0,0,0,0,16,16
"Calaveras, California, US",0,0,2,2,2,12,10
"Colusa, California, US",0,0,0,0,0,3,3
"Contra Costa, California, US",0,0,39,41,46,685,646
"Del Norte, California, US",0,0,0,0,0,2,2
"El Dorado, California, US",0,0,0,0,0,36,36
"Fresno, California, US",0,0,2,3,6,311,309
"Glenn, California, US",0,0,0,0,0,4,4
"Humboldt, California, US",0,0,1,1,1,52,51
"Imperial, California, US",0,0,2,2,4,155,153
"Inyo, California, US",0,0,0,0,0,18,18
"Kern, California, US",0,0,1,3,4,610,609
"Kings, California, US",0,0,0,0,0,20,20
"Lake, California, US",0,0,0,0,0,6,6
"Lassen, California, US",0,0,0,0,0,0,0
"Los Angeles, California, US",0,1,190,231,292,12021,11831
"Madera, California, US",0,0,1,1,3,33,32
"Marin, California, US",0,0,15,15,38,187,172
"Mariposa, California, US",0,0,0,0,0,0,0
"Mendocino, California, US",0,0,0,1,1,5,5
"Merced, California, US",0,0,0,0,0,86,86
"Modoc, California, US",0,0,0,0,0,0,0
"Mono, California, US",0,0,0,0,0,23,23
"Monterey, California, US",0,0,2,4,5,119,117
"Napa, California, US",0,0,0,0,0,47,47
"Nevada, California, US",0,0,1,1,1,36,35
"Orange, California, US",0,1,29,53,65,1556,1527
"Placer, California, US",0,0,9,9,9,131,122
"Plumas, California, US",0,0,0,0,0,4,4
"Riverside, California, US",0,0,16,22,28,2457,2441
"Sacramento, California, US",0,0,40,45,53,914,874
"San Benito, California, US",0,0,3,3,5,44,41
"San Bernardino, California, US",0,0,3,5,9,1219,1216
"San Diego, California, US",0,0,60,80,127,2158,2098
"San Francisco, California, US",0,0,51,70,76,1137,1086
"San Joaquin, California, US",0,0,14,17,25,400,386
"San Luis Obispo, California, US",0,0,7,13,16,131,124
"San Mateo, California, US",0,0,80,89,100,838,758
"Santa Barbara, California, US",0,0,2,8,9,373,371
"Santa Clara, California, US",0,0,175,189,196,1870,1695
"Santa Cruz, California, US",0,0,13,14,15,101,88
"Shasta, California, US",0,0,1,1,1,26,25
"Sierra, California, US",0,0,0,0,0,0,0
"Siskiyou, California, US",0,0,0,0,0,5,5
"Solano, California, US",0,0,8,8,13,169,161
"Sonoma, California, US",0,0,8,6,9,180,172
"Stanislaus, California, US",0,0,5,5,5,206,201
"Sutter, California, US",0,0,0,0,0,25,25
"Tehama, California, US",0,0,0,0,0,1,1
"Trinity, California, US",0,0,0,0,0,0,0
"Tulare, California, US",0,0,4,7,7,397,393
"Tuolumne, California, US",0,0,0,0,0,2,2
"Ventura, California, US",0,0,10,13,19,396,386
"Yolo, California, US",0,0,4,5,5,126,122
"Yuba, California, US",0,0,0,0,0,15,15
"Out of CA, California, US",0,0,0,0,0,0,0
"Unassigned, California, US",0,0,0,0,0,0,0

In [10]:
#Calculating infection number after shelter at home 
infection_number_shelter = ca_key_date_df['Infection number after shelter at home'].sum()
infection_shelter_start = ca_key_date_df['3/18/20'].sum()
infection_to_date = ca_key_date_df['4/18/20'].sum()

print(f"Total infection to 03/18/20: {infection_shelter_start} people")
print(f"Total infection to 04/18/20: {infection_to_date} people")
print(f"There are {infection_number_shelter} infection after shelter at home was ordered")

Total infection to 03/18/20: 828 people
Total infection to 04/18/20: 30491 people
There are 29663 infection after shelter at home was ordered

In [9]:
new_york_df = df.loc[df['Province_State'] == 'New York']
new_york_df = new_york_df.drop(['Admin2','Province_State','Country_Region','UID','iso2','iso3','code3','FIPS','Lat','Long_'],axis = 1)
new_york_df = new_york_df.set_index('Combined_Key')
new_york_df.head()

,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,1/30/20,1/31/20,...,4/12/20,4/13/20,4/14/20,4/15/20,4/16/20,4/17/20,4/18/20,4/19/20,4/20/20,4/21/20
Combined_Key,,,,,,,,,,,,,,,,,,,,,
"Albany, New York, US",0,0,0,0,0,0,0,0,0,0,...,478,499,535,548,581,619,648,682,687,704
"Allegany, New York, US",0,0,0,0,0,0,0,0,0,0,...,26,26,28,28,28,29,30,30,30,30
"Bronx, New York, US",0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
"Broome, New York, US",0,0,0,0,0,0,0,0,0,0,...,126,133,146,153,167,178,186,192,199,205
"Cattaraugus, New York, US",0,0,0,0,0,0,0,0,0,0,...,28,28,32,32,32,34,34,34,34,35